channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter>=1.0.0
  - jupyterlab>=2.2.8
  - matplotlib>=3.3.3
  - numpy>=1.19.1,<2.0.0
  - pandas>=1.1.0
  - pandas-datareader>=0.9.0
  - pip>=20.0.2
  - pyarrow>=0.15.1
  - pyasn1>=0.4.8
  - pyasn1-modules>=0.2.7
  - pyspark>=3.0.1
  - pytables>=3.6.1
  - python=3.7
  - scikit-learn>=0.23.2
  - scipy>=1.5.2
  - seaborn>=0.10.1
